### ISSUE TITLE
PSR-1 standards check

### ISSUE THREAD

**Issue by h-shvedko** [leonn00albert/Artemis#18]
Hi Leon,

Here you can find PSR-1 standards https://www.php-fig.org/psr/psr-1/

I found some issues with following to PRS-1 standard in your code. Here are some of them:
1) Files MUST use only <?php and <?= tags. - i saw some your files have closing PHP tag "?>"
2) Namespaces and classes MUST follow an "autoloading" PSR: [[PSR-0](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-0.md), [PSR-4](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-4-autoloader.md)]. - In my commit into branch psr-1 you yon find how to use namespaces
3) Please also check this "Class names MUST be declared in StudlyCaps." also folers has to start with uppercase
4) Method names MUST be declared in camelCase().

**Comment by leonn00albert** [comment]
I think i have updated all the existing files to the psr-1 standard
